-- ==========================================================================
-- CƠ SỞ DỮ LIỆU CLOUD SUPABASE - THCS PHƯỚC HƯNG (AN GIANG)
-- URL Project: https://qoyppvklftetrutmgwfk.supabase.co
-- Giáo viên Tổng phụ trách Đội: Cô Nguyễn Thị Ngọc Nga
-- ==========================================================================

-- 1. Bảng lưu trữ Đăng ký Lịch hẹn Tư vấn Ẩn danh (SUPABASE)
CREATE TABLE IF NOT EXISTS public.anonymous_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    secret_code VARCHAR(30) UNIQUE NOT NULL,      -- Mã tra cứu bí mật (VD: PH-8839-X)
    topic VARCHAR(150) NOT NULL,                  -- Chủ đề tư vấn
    student_grade VARCHAR(30) NOT NULL,            -- Khối lớp (Khối 6, 7, 8, 9)
    preferred_date DATE NOT NULL,                 -- Ngày hẹn gặp Cô Ngọc Nga
    preferred_time VARCHAR(100) NOT NULL,         -- Giờ hẹn gặp
    content TEXT NOT NULL,                        -- Nội dung chia sẻ / tâm sự
    status VARCHAR(30) DEFAULT 'PENDING',         -- PENDING, APPROVED, COMPLETED
    teacher_reply TEXT DEFAULT '',                -- Phản hồi bí mật từ Cô Ngọc Nga
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Bảng lưu trữ Nhật ký Trò chơi Kỹ năng
CREATE TABLE IF NOT EXISTS public.game_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_category VARCHAR(100) NOT NULL,          -- school_violence, cyberbullying, drowning_prevention...
    score INT DEFAULT 10,
    badge_earned VARCHAR(100) DEFAULT 'Kỹ năng vàng',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Bảng Nhật ký AI Tư vấn 24/7 (Bảo mật Ẩn danh)
CREATE TABLE IF NOT EXISTS public.ai_counseling_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(100) NOT NULL,
    emotion_detected VARCHAR(50),
    topic_category VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. BẬT QUYỀN TRUY CẬP ROW LEVEL SECURITY (RLS POLICIES CHO VỚI CHUẨN ANON & SERVICE ROLE)
ALTER TABLE public.anonymous_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_counseling_logs ENABLE ROW LEVEL SECURITY;

-- Cho phép quyền ANON PUBLIC (Học sinh) Thêm mới và Tra cứu
DROP POLICY IF EXISTS "Cho phap hoc sinh tao va tra cuu" ON public.anonymous_bookings;
CREATE POLICY "Cho phap hoc sinh tao va tra cuu" ON public.anonymous_bookings
    FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Cho phap hoc sinh ghi log game" ON public.game_logs;
CREATE POLICY "Cho phap hoc sinh ghi log game" ON public.game_logs
    FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Cho phap luu log ai" ON public.ai_counseling_logs;
CREATE POLICY "Cho phap luu log ai" ON public.ai_counseling_logs
    FOR ALL USING (true) WITH CHECK (true);

-- 5. KÍCH HOẠT TÍNH NĂNG SUPABASE REALTIME REPLICATION (THỜI GIAN THỰC)
ALTER PUBLICATION supabase_realtime ADD TABLE public.anonymous_bookings;

-- SEED DATA MẪU BAN ĐẦU
INSERT INTO public.anonymous_bookings (secret_code, topic, student_grade, preferred_date, preferred_time, content, status, teacher_reply)
VALUES 
('PH-8839-X', 'Phòng chống Bạo lực học đường', 'Khối 8', '2026-08-07', 'Giờ ra chơi sáng (9:15 - 9:30)', 'Em cảm thấy bị một bạn học khác lớp liên tục chặn đường hù dọa mỗi khi tan học.', 'APPROVED', 'Chào em! Cô Ngọc Nga đã nhận được thông tin. Em yên tâm nhé, thứ Sáu tuần này giờ ra chơi 9:15 em hãy lên văn phòng Đội gặp cô. Cô sẽ bảo vệ em an toàn!'),
('PH-9821-K', 'Phòng chống Bắt nạt không gian mạng', 'Khối 7', '2026-08-08', 'Sau giờ học buổi chiều', 'Có một tài khoản Facebook ẩn danh liên tục nhắn tin chửi bới và đe dọa em.', 'PENDING', '')
ON CONFLICT (secret_code) DO NOTHING;
